Transaction Logging Python Skeleton
18F/identity-give-transaction-logging pull request #5
Opened 2020-12-10 22:50 UTC by zclarkEDC

Skeleton of Transaction Logging Microservice in Python Chalice. 
Set up partial DB integration for creating and retrieving simple items.

2020-12-10 22:54 UTC, folksgl requested changes

2020-12-10 22:54 UTC, folksgl commented on .gitignore
> +.chalice/venv/
Please add .chalice/deployed/

2020-12-10 22:54 UTC, folksgl commented on app/.chalice/config.json
> +  "app_name": "app",
The app_name should match the pattern:
github repo = identity-give-<app_name>
so here it should be "transaction-logging"

2020-12-10 22:54 UTC, folksgl commented on app/.chalice/deployed/dev.json
> +{
This needs to be taken out of the git history. We're not tracking chalice state files.

2020-12-11 19:34 UTC, zclarkEDC commented on app/.chalice/deployed/dev.json
> +{
fixed with [removed deployed folder](https://github.com/18F/identity-give-transaction-logging/pull/5/commits/84a4678c14923577777dda038ede549c1be9861a)

2020-12-14 14:31 UTC, closed without merging